### ISSUE TITLE
Improve writing performance of extra files

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#161]
PISM currently writes to the extra file at each time step requested for reporting. When the user asks for very long, temporally-dense time-series, this results in a performance hit that makes such simulation unfeasible. Consider:

```
-extra_times 0:yearly:500000 -ys 0 -ye 500000
```

and

```
-extra_times 0:yearly:500000 -ys 0 -ye 500000 -extra_split
```

Runtime increase for both examples, compared to the same run without extra file reporting is exorbitant, even with pnetcdf (which seems to be faster than netcdf3 and netcdf4_parallel). This is true even for very coarse grids. For the above examples, writing the extra fields alone would take a total 138h, if each time slice takes about a second to write. Also, according to ARSC, writing a file every second may lead to serious performance hits for other ARSC users on the same system, and thus not very appreciated by ARSC (thus -extra_split is not really an option).

I'm afraid I'm not the expert here, so I'm just trying to repeat here a discussion between Greg Newby and Constantine: The upshot is that it would probably more efficient to cache a number of time slices (number may depend on grid size?) and aggregate them, then writing it to the disk. Maybe write a file per variable.

**Comment by ckhroulev** [comment]
This issue is no longer relevant because raw I/O performance is no longer an issue. File *sizes* **are** an issue, but that's a different story.

My tests show that in a whole-Greenland run using a 1km grid PISM can write all the variables requested by ISMIP6 in 2/3 of a second. In a 500,000-year run like this one I/O would take a little less than 100 hours. However, the resulting file would take up about 250 Tb of storage space, so clearly I/O speed is not an issue.

Also note that ParallelIO + PnetCDF can aggregate data over multiple records and multiple variables.
