### ISSUE TITLE
short "how to" for debugging PISM

### ISSUE THREAD

**Issue by matthiasmengel** [pism/pism#293]
Hi,

I just realized that I always run into problems when I have to debug stuff that is hidden too deep in parallelized code, that is, I do not really know how to efficiently debug in parallel mode.

Can we have a short "how to" in the manual how to debug PISM?
I find these points relevant:
- how do I have to compile PETSC? I guess --with-debugging=1
- which PISM compile flags should be set? I guess -DPISM_DEBUG=1
- which MPI version should I use?
- which are the options I should run PISM with? PETSC suggest Try option -start_in_debugger or -on_error_attach_debugger which starts gdb after the error but does not provide any more insight.
- What is a good workflow when debugging PISM in parallel, which are the tools to use?

I am sure we could collect some sentences on that. It would be great to have them documented somewhere.

Matthias

**Comment by ckhroulev** [comment]
Matthias,

Dang. It's been five years since you opened this issue, and I still don't know how to give you a good answer. Please take a look at [`development-workflow.rst`](https://github.com/pism/pism/blob/72c3a89daf75c687e1f1203877d16a4f2fbd8ff9/doc/sphinx/contributing/development-workflow.rst) and let me know if this comes close to addressing your questions.

**Comment by ckhroulev** [comment]
I've written up everything I could think of on this topic (see the link above).

Please re-open this issue if you have more questions.
