### ISSUE TITLE
Building PISM on Cray (XC30)

### ISSUE THREAD

**Issue by jsegu** [pism/pism#316]
It turned out to be harder to configure and build PISM on a Cray than on supercomputers that I have used before, and I think some changes could be made in PISM to make it a bit easier. There is more than one issue and more than one solution in this report, but I thought it would be useful to summarize all the problems I had here to help you decide what need to be changed.

I think there are two ways to configure PISM to build on a Cray using static libs, and that both are problematic now.

### 1. Find packages using CMake
Using `Pism_LOOK_FOR_LIBRARIES "ON"` (the default). This is my preferred way as I feel I have better control on which libraries are being used.

**Problem:** On the system that I use PETSc libraries have very specific file names such as `libcraypetsc_gnu_real.a` instead of `libpetsc.a`. Currently there is no way to tell CMake to look for a file named something else than `libpetsc.a`.

**Tested solution:** Remove the following line in `FindPETSc.cmake`

    set (PETSC_LIBRARY_${suffix} "NOTFOUND" CACHE INTERNAL "Cleared" FORCE) # Clear any stale value, if we got here, we need to find it again

After this I am able to inform CMake of the exotic file name through the config variable `PETSC_LIBRARY_SINGLE`. Before looking at `FindPETSc.cmake` I was also wondering why this had no effect. Or am I missing something here?

**Tested workaround:** Use an user-installed PETSc with regular file names instead of the Cray version.

### 2. Let the module system find libraries
Using `Pism_LOOK_FOR_LIBRARIES "OFF"`. This is what is recommended in the Cray (XK6) section of the manual, however not my preferred choice.

**Problem:** Contrary to what is written in the manual, CMake's `include_directory` function has no effect when used in a `pism_config.cmake` "pre-configure" file. This though, is not needed for Cray system packages (include directories are set by the module system), nor for mandatory dependencies not part of the system (e.g. GSL, using `GSL_INCLUDES`), but it is a problem for optional dependencies not part of the system (in my case, PROJ.4). As I understand, this is because `PROJ.4_INCLUDES` has no effect if PROJ.4 was not "found" by CMake. That is, it has no effect if PROJ.4 was not found by the CMake find_package mechanism which we just turned off by setting `Pism_LOOK_FOR_LIBRARIES "OFF"`. See the code from `PISM_CMake_macros.cmake`.

**Untested solution 1:** Add a `Pism_EXTERNAL_INCLUDES` config variable to allow extra include directories similarly as with `Pism_EXTERNAL_LIBS`.

**Untested solution 2:** Always include `PROJ4_INCLUDES` and friends (from other optional dependencies), independently of whether these packages were "found".

**Tested workaround:** Add optional, user-installed includes paths into the include path of some required dependency, such as `GSL_INCLUDES "/path/to/gsl/include;/path/to/proj4/include/"`.

**Comment by aaschwanden** [comment]
Julien,

Constantine will probably pitch in, as he's our CMake expert. But I agree, Cray computers give a lot of head-ache too. We even ended up compiling our own petsc as Cray was unable to provide a petsc module compiled with 64bit integer support. This required some trial-and-error to find a working combination of modules, and a special config file for cmake.

**Comment by ckhroulev** [comment]
Julien,

Commit 294f40a implements the "untested solution 2" approach (except that I tested it). To specify the PROJ.4 location, set CMake variables `Pism_USE_PROJ4`, `PROJ4_INCLUDES`, and `PROJ4_LIBRARIES`.

This is what worked for me:
``` cmake
set (Pism_USE_PROJ4 ON CACHE BOOL "" FORCE)
set (PROJ4_LIBRARIES "$ENV{HOME}/local/proj4/lib/libproj.a" CACHE STRING "" FORCE)
set (PROJ4_INCLUDES  "$ENV{HOME}/local/proj4/include" CACHE STRING "" FORCE)
```

Please let me know if it works for you.

**PS:** I would argue that this gives you **more** control of what libraries PISM uses compared to the option "Find packages using CMake" that you describe.

On Cray systems you always have to load modules, the only difference is in whether our CMake scripts try to guess where to find header files and libraries. So, we have two possibilities:
 1. Load modules and let CMake look for libraries. Here we have two "black boxes": the module system and CMake scripts.
 2. Load modules and set paths manually. Here we have one "black box": the module system.

In my experience CMake's heuristics rarely work on Crays, so I think it's best to disable them altogether, rather than add one workaround after another every time PISM fails to find a library.

**PPS:** I'm sure you can tell that I am very frustrated with Cray's modules. I'm convinced that they can be used to define both [kluge](http://www.catb.org/jargon/html/K/kluge.html) and [job security](http://www.catb.org/jargon/html/J/job-security.html). (Okay, I'll stop ranting now.)

**Comment by ckhroulev** [comment]
Please feel free to re-open if this is still a problem. (Also, see [`https://github.com/pism/hpc-builds`](https://github.com/pism/hpc-builds).)
