### ISSUE TITLE
horizontal grid meaning: clarify documentation and example runs

### ISSUE THREAD

**Issue by bueler** [pism/pism#347]
- Section 5.2 of pism0.7 manual is not clear on meaning of `-Lx` and `-Ly`, given that the grid points are interpreted as cell centers at bootstrapping.
- For example of what should be better documented, the (shortened & simplified) current Chapter 1 run

```
pismr -i pism_Greenland_5km_v1.1.nc -bootstrap -Mx 76 -My 141 -Mz 101 -Mbz 11 -z_spacing equal -Lz 4000 -Lbz 2000 -skip -skip_max 10 -ys -10 -ye 0 -surface given -surface_given_file pism_Greenland_5km_v1.1.nc -sia_e 3.0
```

generates

```
                run_stats:grid_dx_meters = 19802.6315789474 ;
                run_stats:grid_dy_meters = 19893.6170212766 ;
```

As an example of what the user might try if they want the spacing to be 20 km, adding `-Lx 760 -Ly 1410`, _which would have the effect of putting the extreme grid points on top of the input data grid points_, generates error

```
PISM ERROR: target computational domain not a subset of source (in NetCDF file)
            computational domain:
            target domain: [-810000.000, 710000.000] x [-3410000.000, -590000.000] x [0.000, 0.000] meters
            source domain: [-802500.000, 702500.000] x [-3402500.000, -597500.000] x [0.000, 0.000] meters
```

This error message is clear and correct given current interpretations and bootstrapping meaning.  It tells the user how PISM interpreted their input grid (`source domain`).
-  So the issue is really about documenting intermediate grid behavior, meaning bootstrapping onto a grid coarser than the data, which is the most common case.  Once you refine down to the original data resolution the cell-centered interpretation and the bootstrapping-automatic-extent-determination agree on the 5km spacing of the original data. The question is, what should we tell users about resolution of intermediate grids?

@ckhroulev @aaschwanden :  This issue motivated by correspondence with Nick Golledge.

**Comment by tkleiner** [comment]
I would like to add, that the default default `pism_config:grid_periodicity`  has changed from "none" to "xy"  from stable0.6 to stable0.7.

Instead of 
`
pismr -i bedmap2_pism.nc -bootstrap -x_range -3040000,3040000 -y_range -3040000,3040000 -Mx 191 -My 191 -Mz 10 -Lz 5000 -Mbz 3 -Lbz 2000 -surface elevation -ocean pik -y 0 -o out1.nc
`
one needs 
`
pismr -periodicity none -i bedmap2_pism.nc -bootstrap -x_range -3040000,3040000 -y_range -3040000,3040000 -Mx 191 -My 191 -Mz 10 -Lz 5000 -Mbz 3 -Lbz 2000 -surface elevation -ocean pik -y 0 -o out2.nc
`
to get the expected grid spacing of 32km. At least I was not aware of this change.

**Comment by ckhroulev** [comment]
Closing this because it is fixed in `dev` and will be fixed in the next release (coming soon). See <http://pism-docs.org/sphinx/manual/modeling-choices/computational/grid.html#grid-registration> for now.
