### ISSUE TITLE
Exclude ice shelves from the load in bed deformation models

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism#363]
The title says it all.

_Completely_ excluding the contribution of floating ice is of course wrong. It is better than what we do now, though.

**Comment by talbrecht** [comment]
I'm having a discussions with Pippa Whitehouse on how PISM calculates changes in ice load in marine areas. Pippa suggested, that the bed deformation model should consider changes in 'thickness above buoyancy' rather than full 'ice thickness'. I looked through the 'earth' folder, but could not find any distinction between grounded above sea-level, grounded below sea-level or floating ice (as in the slvol reporting). Hence I thought my question could be related to this task, and I think this is really important for our deglaciation simulations!

**Comment by ckhroulev** [comment]
Done in the `dev` branch. See [`compute_load()`](https://github.com/pism/pism/blob/506aea41f/src/earth/BedDef.cc#L202).
