### ISSUE TITLE
Slow netcdf writing with many processors

### ISSUE THREAD

**Issue by matthiasmengel** [pism/pism#376]
Hi!
I tested 5km Antarctica simulations with 528 cores. Very slow writing of netcdf snapshots
make such task a waste of CPU hours under standard settings.
It would be great to get to know your experience for fast netcdf writing when many CPU are involved.
The pism manual, section `9.1.1` (commit 893e2e4a30934616d7) mentions this shortly, but it is not trivial (at least for me) to get this running.
Should we document somewhere the compiler options to get fast parallel netcdf writing?
Is there any way to measure I/O time against CPU time?
I guess all but the standard options of 
```
    pism_config:output.format = "netcdf3";
    pism_config:output.format_choices = "netcdf3,quilt,netcdf4_parallel,pnetcdf,hdf5";
```
are meant for fast parallel i/o.
@aaschwanden?

**Comment by citibeth** [comment]
Have you tried format = netcdf4_parallel or pnetcdf?  I would try them
first, especially *netcdf4_parallel* (The pnetcdf package is closer to
being obsolete).

**Comment by ckhroulev** [comment]
Sadly fast I/O is something that we are still struggling with.

I would recommend trying `pnetcdf` and `netcdf4_parallel` and comparing timings in your runs. Most likely `pnetcdf` will be faster. The downside is that you cannot use it for high-resolution runs due to a NetCDF-3 file format limitation, so if you get an error saying that your grid is too big to fit in a NetCDF-3 file, use `netcdf4_parallel`.

The `quilt` option writes one file per core ("poor man's parallel I/O"). I would call this a failed experiment. Writing is pretty fast, but post-processing is a mess. Not recommended. (I should probably remove the code implementing it.)

The code implementing the `hdf5` option never got past the experimental stage and I need to remove it. I already removed it once, but a user asked me to resurrect it. Not recommended (and does not support HDF5 1.10.x).

> Is there any way to measure I/O time against CPU time?

Run `pismr` with the option `-profile profiling_output.py` and then run `plot_profiling.py profiling_output.py`. You can find `plot_profiling.py` in the `util` directory in the PISM source tree.

This will produce a number of pie charts like this one.

![profiling](https://cloud.githubusercontent.com/assets/1018111/23560759/068309ce-ffe8-11e6-9021-6d8f42dbd292.png) 

PS: As far as I know the [Parallel NetCDF](https://trac.mcs.anl.gov/projects/parallel-netcdf) library is not obsolete and I suspect it will not be any time soon. NetCDF-4 based on HDF5 is more flexible, but PnetCDF uses a simpler file format (and has a lower overhead). Moreover, PnetCDF developers seem to pay more attention to performance issues and have the ability to address them, unlike NetCDF-4 developers who  are spread pretty thin and rely on the HDF Group for all low-level optimizations.

**Comment by citibeth** [comment]
Constantine,

Thank you for the informed response and update.

Our GCM uses the NetCDF-3 format; either with the NetCDF library or
pnetcdf.  The problem with this (for ice coupling) is that only a small
fraction of landice-related grid cells are used.  Switching/converting to
(compressed) NetCDF-4 format results in a 95% reduction in file size.

-- Elizabeth

**Comment by ckhroulev** [comment]
@citibeth Good point!

**Comment by matthiasmengel** [comment]
Hi again and thanks a lot for your help!

Parallel netcdf writing now works, here is what I needed to do:

* use a netcdf4 version that was compiled for parallel use
   (I did not build this myself, otherwise I would provide more details.)

* compile PISM with cmake flag `-DPism_USE_PARALLEL_NETCDF4:BOOL=ON`

* run PISM with option `-o_format netcdf4_parallel`

* specific for HPCs using a module system: make sure that all modules used for compilation are present when the job is submitted, especially the parallel netcdf4 module.

In a test, I let the model run on 5km resolution for complete Antarctica, running for 1 model year and writing snapshots at year zero and year 1 and the final output file. Each of the three has a size of `5.9GB` with 

```
	time = UNLIMITED ; // (1 currently)
	x = 1200 ;
	y = 1200 ;
	z = 201 ;
	zb = 51 ;
```

The run finishes within 6 minutes on 512 cores, with I/O consuming less than 90 seconds of that time. I think that is quite good as one would normally write output much less frequent.

Thanks again!
Matthias

**Comment by ckhroulev** [comment]
@matthiasmengel I'm glad to hear that you made it work! However, 5.9 Gb in 90 seconds is just over 67 Mb/s, which is pretty bad. I still need to work on this.

**Comment by matthiasmengel** [comment]
Let me know then if I can help with tests.

The run was profiled with darshan, http://www.mcs.anl.gov/research/projects/darshan/, which gave also
```I/O performance estimate (at the MPI-IO layer): transferred 76804 MiB at 517.29 MiB/s```
A bit better number, though I do not know why this is so different to your calculation.

**Comment by ckhroulev** [comment]
Commit b3f1050a5e84fe22f0b18767fcd4c9759c07cd88 adds detailed documentation explaining how to get better I/O performance. This change is in the `dev` branch and will be a part of the next release.
