### ISSUE TITLE
bmelt not written for ice shelves in pism-dev

### ISSUE THREAD

**Issue by matthiasmengel** [pism/pism#386]
I find `bmelt=0` for all ice shelf area in the pism-dev 893e2e4a30934616 searise antarctica example. This is already evident in the smoothing_30km.nc file. 

I noticed this in new simulation for the Antarctic ice sheet that have unreasonably spreading ice shelves. As bmelt reflects the internal variable `basal_melt_rate`, I wonder if ice shelves see the ocean basal melting or if it is only a problem of bmelt diagnostic.

**Comment by ckhroulev** [comment]
Matthias,

Here's the problem: in older PISM versions `bmelt` was modified in two places: in the energy model step and in `IceModel` (using data provided by an ocean model).

Not so long ago I isolated energy balance models in the `dev` branch. PISM's energy balance models "own" the basal melt rate because it is a part of their "state", but *they can compute it at grounded locations only*.

`IceModel` then combines this field with the sub-shelf melt rate provided by an ocean model. Both fields (grounded-only and combined) were called "`bmelt`", leading to confusion.

I renamed the energy-model-managed basal melt rate field to `basal_melt_rate_grounded`. `bmelt` (the combined field) is still available as a diagnostic under the old name.

So, as far as I can tell, `bmelt` being zero in floating areas is a reporting issue.

Regarding "unreasonably spreading ice shelves": I need a more specific report to figure out what is going on and to address it (if necessary). As usual, please see [PISM's bug reporting guidelines](http://pism-docs.org/wiki/doku.php?id=reporting_bugs) for more.

**Comment by matthiasmengel** [comment]
Constantine,
thanks for the explanation. In follow-up runs I see better ice shelves, so I think it is a reporting issue only (and still).

Would it make sense to have a `basal_melt_rate_floating` next to `basal_melt_rate_grounded`? I think users would be looking for the floating one when seeing the grounded one, and then be irritated if it does not exist. `bmelt` could still combine the two.

**Comment by ckhroulev** [comment]
In the `dev` branch and the upcoming release you have the following choices:

- `bmelt` (combined grounded and floating basal melt rate in ice equivalent thickness per time). Note that the model state variable `bmelt` is different: it is grounded-only and is zero in floating areas.
- `basal_mass_flux_grounded` (the grounded basal mass flux in `kg m-2 year-1`)
- `basal_mass_flux_floating` (same as `_grounded`, but for shelves)
- `tendency_of_ice_amount_due_to_basal_mass_balance`, the combined (grounded and floating) basal mass flux in `kg m-2 year-1`

So, I'm closing this.
