### ISSUE TITLE
Sea-level equivalent volume calculation using sea water or fresh water density? 

### ISSUE THREAD

**Issue by talbrecht** [pism/pism#412]
In literature you find sea-level relevant volume for the present-day Antarctic Ice Sheet of around 58m, as already mentioned in the bugfix #388. In the sealevel_volume() calculations in diagnostics.cc we first calculate the volume below flotation (using the density fraction of ice and seawater), as in ice_volume_not_displacing_seawater(). In order to calculate the sea-level change considering melted ice discharge into the ocean, we rather should use the ratio of ice and freshwater densities instead?! This would lead to a minor change of 56.85m to 58.45m for Bedmap2 dataset. Maybe it is worth a discussion?!

**Comment by florianziemen** [comment]
Moin!

Hmm, that indeed is an interesting question. There’s a lot of messiness in these density things. In the end, it depends on what temperature and salinity you assign to the newly formed water. If you mix a liter of warm water with a liter of cold water, you get a bit less than two liters of water… (try the math here: https://www.mt-oceanography.info/Utilities/density.html) 
So, if you take an ocean and keep its mean temperature and salinity constant, while mixing it a bit better, you end up with having “less” water at the end… 

Also, if you really take Antarctica out, the bedrock is going to rebound there … 

Might be better to just look at changes than at absolute values, because there simply are too many assumptions in these numbers, and seriously, if we completely melt Antarctica, the last two meters might not be our biggest concern).

Basically, if you take Antarctica and leave it as a solid, and spread it out over the oceans, so everything swims, the sea level rise is the low number resulting from taking the sea water density (Archimedes). Well, actually the oceans will expand into land, so the increase is a bit smaller, as you can flood all of Northern Germany and a bunch of other places - hello Florida. 

> If you then melt the ice you just created, and turn it into a freshwater lens swimming on the other water, you get a higher number (computed with freshwater density). [ This probably is a good first approx for the global sea level rise resulting from melting Antarctica ] <

If that (cold and fresh) water then mixes into the overall ocean the density increases a bit again, and your sea level falls a bit.

But you probably also have global warming (and thus ocean warming) reducing the ocean density, and thus the sea level will rise anyways.

Just my two cents.

Flo


> On Jun 12, 2018, at 15:50, Torsten Albrecht <notifications@github.com> wrote:
> 
> In literature you find sea-level relevant volume for the present-day Antarctic Ice Sheet of around 58m, as already mentioned in the bugfix #388. In the sealevel_volume() calculations in diagnostics.cc we first calculate the volume below flotation (using the density fraction of ice and seawater), as in ice_volume_not_displacing_seawater(). In order to calculate the sea-level change considering melted ice discharge into the ocean, we rather should use the ratio of ice and freshwater densities instead?! This would lead to a minor change of 56.85m to 58.45m for Bedmap2 dataset. Maybe it is worth a discussion?!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Florian Ziemen

Tel: +49 176 2151 8599
Tel: +49 40 2879 2445
skype: floziemen
http://iceflo.de

**Comment by citibeth** [comment]
If the sea level rises 58m, I don't think anyone will be too worried about
+- 40cm.

**Comment by talbrecht** [comment]
I agree this has not so much to do with a actual collapse of the entire ice sheet, and I actually brought this into discussion for consistency reasons as people use sea-level equivalents (SLE) as handy unit, but they do it in different ways. For instance if you compare paleo simulations of the Antarctic Ice Sheet and people have 58m SLE in mind as present day value, they might be irritated if best-fit simulations end up at 56.5m SLE. This makes only 3% difference also for anomalies, but still it seems worth discussing. 
In the SeaRISE intercomparison they defined volume above flotation (VAF) with a conversion factor of "4.0x10^14 m3 of ice (above flotation) equates to a 1 m rise in mean global sea level" (Bindschadler et al., 2013). Unfortunately they did not mention what ice density they assumed. For an ocean surface of 361x10^12m2 we would end up with a possible ratio of ice density of 902kg/m^3 and fresh water density of 1000kg/m^3 or a ration of ice density of 927kg/m^3 and ocean water density of 1027kg/m^3.

**Comment by florianziemen** [comment]
Oh, I just take that as a rule of thumb. 1e15 m3 of ice are about 2.5 m SLE. Works astonishingly well. I wouldn’t be surprised if they just decided that this is much nicer than an exact value of 2.4829874579 (or whatever your preferred numbers yield).

In the end, this really mostly is about consistency. Once our sea level change projections have error bars of about 10%, we can actually start thinking about the exact conversion factors. I still think, we should use freshwater density to convert ice into sea level equivalent (and we might want to think about how to handle this in the context of the whole floatation criterion). 

Cheers

Flo

**Comment by talbrecht** [comment]
Ok, I would also support using the ratio of fresh water density and PISM default ice density of 910kg/m3 for the conversion, but I also don't see the need for an immediate change. Let's keep this in mind then.

**Comment by fmaussion** [comment]
I am the developer of the [Open Global Glacier Model](http://oggm.org/) (https://github.com/OGGM/oggm) and I wanted to say hi! 

This is probably not the right place to discuss this, but I think it would be good that the three communities (SLR, Ice Sheet, Mountain glaciers) agree on a way to compute SLR equivalent. Note that the [GlacierMIP](http://www.climate-cryosphere.org/activities/targeted/glaciermip/activities-experiments) recommends the following: 

> 6) Assuming density of ice = 900 kg/m3 for conversion of glacier volume to mass
> 
> 8) Assuming ocean area of 362.5 x10^6 km2 (following Cogley et al. 2011) to convert volume change to sea-level equivalent.

cc @bmarzeion

**Comment by talbrecht** [comment]
Thanks for your input @fmaussion, and I guess you neglect volume changes of the meltwater due to mixing with the ocean water? Assuming a density of Antarctic ice of 910kg/m3 as default in PISM and a slightly larger ocean surface brings us very close to the above mentioned SeaRISE conversion factor (-0.4%) and to an Bedmap2 SLE of 58.2m.

**Comment by talbrecht** [comment]
This would be the corresponding fix: #413

**Comment by ckhroulev** [comment]
#413 is merged into `dev`, so I think we can close this now.
