### ISSUE TITLE
Restart issue caused by calendar in 0.7/1.0/dev

### ISSUE THREAD

**Issue by tkleiner** [pism/pism#422]
PISM's earth deformation models `-bed_def [iso, lc]` update every 10 years (default). This interval can be changed via config or command-line settings. PISM converts this interval into seconds using UDUNITS. Unfortunately, a year in udunits is 365.2524 days long and thus longer than an e.g. 365_day calendar year. The causes a delay in the bed deformation update time that leads to large differences (in set-ups with more physics) between restarted runs and "straight" runs. In the example beleow the restarted run shows the expected behaviour and not the straight run. 

How to test:
I have extended the regression test from `PISM_BASE_DIR/pism1.0/test/regression/bed_def_lc_restart.sh` to reproduce this issue for PISM 0.7/1.0/dev ([bed_def_lc_restart_sh.txt](https://github.com/pism/pism/files/2548387/bed_def_lc_restart_sh.txt), [pism_stable1.0_batch.txt](https://github.com/pism/pism/files/2548401/pism_stable1.0_batch.txt)). 
In this test `-calendar 365_day` is used, because of simplicity. Results obtained by using `-calendar none` are even worse. Plotting can be done with a modified version of tsshow.py ([tsshow_py.txt](https://github.com/pism/pism/files/2548403/tsshow_py.txt)). 

The figure below shows the result of different pism versions. Note also the difference between stable1.0 and dev.

![topg_all_pism_versions_2x2](https://user-images.githubusercontent.com/5449934/47999223-30d13000-e102-11e8-80aa-6d5db0103ba4.png)

PISM versions: 
- PISM stable v0.7.3-20-g9cfa7c
- PISM (stable v1.0-35-g9b1b6ff committed by Torsten Albrecht on 2018-03-14 11:04:20 -0800)
- PISM (development v1.0-760-g2cc8c0b committed by Constantine Khrulev on 2018-11-01 21:05:49 -0800)

Below you can find my proposed (partial) fix for the Lingle and Clark model in stable0.7, but this conversion should be done somewhere else in the code and in a more general way to avoid code duplication not only in other earth deformation models. 

In `void PBLingleClark::update_with_thickness_impl(...)` from `src/earth/PBLingleClark.cc` replace 
```
  if ((dt_beddef < m_config->get_double("bed_def_interval_years", "seconds") and
       t_final < m_grid->ctx()->time()->end()) or
      dt_beddef < 1e-12) {
    m_log->message(2, " tkleiner: return early!\n");
    return;
  }
```
by 
```
  // partial fix starts here
  double dt_beddef_interval = m_config->get_double("bed_def_interval_years", "seconds");
  std::string calendar = m_config->get_string("calendar");
  if (calendar == "360_day") {
    dt_beddef_interval = m_config->get_double("bed_def_interval_years");
    dt_beddef_interval *= 360.0 * 86400.0;
  } else if (calendar == "365_day" or calendar == "noleap") {
    dt_beddef_interval = m_config->get_double("bed_def_interval_years");
    dt_beddef_interval *= 365.0 * 86400.0;
  } else {
    //todo: "none", "standard", "gregorian", "proleptic_gregorian", "julian"
    m_log->message(2, " PBLingleClark::update_with_thickness_impl(...): \n",
        "invalid calendar <%s> for year to second conversion\n", calendar.c_str());
  }
  if ((dt_beddef < dt_beddef_interval and
       t_final < m_grid->ctx()->time()->end()) or
      dt_beddef < 1e-12) {
    return;
  }
```
May inconsitent use of the calendar is also the reson for #407. 

P.S.: I would like to thank Hu Yang who initially reported this issue to me.

**Comment by ckhroulev** [comment]
@tkleiner Thanks for reporting this!

The real issue here is that the Lingle-Clark bed deformation model does not use the same (consistent and predictable) time step length. The "update interval" controlled by `bed_deformation.update_interval` is actually the *minimal* length of a time step this model can take.

Back when this model was originally implemented the reasoning was that the numerical method does not have a time-step restriction and the time scale of bed deformation is slower than the one of ice dynamics, so we should be able to say "don't update the bed topography more often than every X years -- that would be a waste of time". This is the real meaning of `bed_deformation.update_interval`.

This means that if stability restrictions coming from the rest of the model allow a 100-year time step the bed deformation model will happily take a 100-year time step even if `bed_deformation.update_interval` is set to 10 years.

I definitely need to fix this. The only consistent and predictable way of handling this that I can think of is by treating `bed_deformation.update_interval` as a time-step restriction *and* using a separate time line for bed deformation models (similar to updates of energy balance models when "skipping" is enabled). This way the user (you) will be able to decide what time scale for bed deformation is relevant in your case and have the model updated exactly that often through asynchronous coupling of bed deformation to the rest of PISM.

PS: This *would* make PISM runs using bed deformation models slightly more expensive, but for a good reason.

PPS: I realize that the issue I described in this comment is different from the one reported, but a proper fix will take care of both of them.

**Comment by ckhroulev** [comment]
This issue should be fixed in the `master` branch.

I used the script below to check.

``` bash
#!/bin/bash

# stop on error
set -e

pism_path=~/local/pism/bin
mpi="mpiexec -n 2"

# use a non-square grid
Mx=41
My=61
grid="-Lz 5000 -Mz 3 -Mx ${Mx} -My ${My}"

# bed deformation update interval
bed_dt=10

phys="-bed_def lc -extra_times 5 -extra_vars topg -stress_balance none -energy none -verbose 2"

update_interval="-bed_deformation.lc.update_interval ${bed_dt}"

create_input_file () {
${mpi} ${pism_path}/pisms ${grid} -y 1000 -o spinup.nc -verbose 1
}

uninterrupted () {
${mpi} ${pism_path}/pismr ${options} -bootstrap ${grid} \
  -i spinup.nc \
  -o uninterrupted-out.nc \
  -extra_file uninterrupted-ex.nc \
  -ts_file uninterrupted-ts.nc \
  -ts_times 0.1 \
  -ys 0 -ye 60
}

interrupted () {
dt=10
ye=${dt}
rm -f interrupted-ex.nc
${mpi} ${pism_path}/pismr ${options} -i spinup.nc \
       -o interrupted-out-0.nc \
       -extra_file interrupted-ex.nc \
       -ys 0 \
       -ye ${ye} \
       -ts_file interrupted-ts.nc \
       -ts_times 0.1 \
       -bootstrap ${grid}

for i in {0..4}; do
  ye=$((ye + dt))
  ${mpi} ${pism_path}/pismr ${options} \
         -i interrupted-out-${i}.nc \
         -o interrupted-out-$(( i + 1 )).nc \
         -extra_file interrupted-ex.nc \
         -extra_append \
         -ts_file interrupted-ts.nc \
         -ts_times 0.1 \
         -ts_append \
         -ye ${ye}
done
}

# create an input file
create_input_file

for calendar in 365_day 360_day none;
do
  echo "Calendar:" ${calendar}
  options="${phys} -calendar ${calendar} ${update_interval}"

  # clean up
  rm -f interrupted-{out-*,ex}.nc
  rm -f uninterrupted-{out,ex}.nc

  # run without restarting
  uninterrupted

  # run with stopping and re-starting
  interrupted

  # compare results
  nccmp.py -v topg uninterrupted-ex.nc interrupted-ex.nc

  nccmp.py -v topg,thk,dbdt uninterrupted-out.nc interrupted-out-5.nc
done
```
