### ISSUE TITLE
tendlibmassbf ISMIP6 output in dev

### ISSUE THREAD

**Issue by tkleiner** [pism/pism#445]
In 'src/icemodel/diagnostics.cc' the ISMIP6 variable 'tendlibmassbf' is computed as 'basal_mass_flux_grounded'. I think this is not correct and should be 'basal_mass_flux_grounded + basal_mass_flux_floating' according to Table A1: Variable request for ISMIP6 projections ([Antarctica](http://www.climate-cryosphere.org/wiki/index.php?title=ISMIP6-Projections-Antarctica) and [Greenland](http://www.climate-cryosphere.org/wiki/index.php?title=ISMIP6-Projections-Greenland)). 

Screenshot (3. Dec 2019)

![Screenshot 2019-12-03 at 11 00 44 ](https://user-images.githubusercontent.com/5449934/70041616-c8cb7280-15bd-11ea-9efd-5b2039eb1568.png)

Edit:
Also, 'dlithkdt' is a flux variable and thus needs to be averaged over the reporting interval. I think this should be 'tendency_of_ice_amount / density' instead of 'dHdt' calculated as (H -H_last)/dt in `class ThicknessRateOfChange : public Diag<IceModel>`.

**Comment by ckhroulev** [comment]
> In `src/icemodel/diagnostics.cc` the ISMIP6 variable `tendlibmassbf` is computed as `basal_mass_flux_grounded`. I think this is not correct and should be `basal_mass_flux_grounded + basal_mass_flux_floating`

Thanks for reporting this! This is corrected in 32bcaf7e4fe27b6508f153d42ad6e932fe744a08. 

> `dlithkdt` is a flux variable and thus needs to be averaged over the reporting interval

It is *already* averaged over the reporting interval: it is computed as `(H - H_last) / reporting_interval`, not `(H - H_last) / dt` with `dt` from stability criteria.

Note that for some fluxes (the SMB, for example) the total amount added at a given location may grow indefinitely even if the system is at a steady state. To compute these fluxes we need to accumulate changes at each time step during a reporting interval and divide by the interval length at the end of a reporting interval. (Keeping track of corresponding cumulative quantities may lead to loss of precision.) `dHdt`, on the other hand, can be computed using ice thickness (its corresponding cumulative quantity): there is no risk of unbounded growth of ice thickness and so no risk of precision loss. And, as a result, no need to accumulate changes at each time step to compute the average rate.

> I think this should be `tendency_of_ice_amount / density`

I disagree. `tendency_of_ice_amount` tracks ice "amount" (mass per unit area) and so includes ice mass in "partially-filled" cells. We cannot assign a particular thickness to the ice mass in a partially-filled cell and so should not compute `dlithkdt` (i.e. `dHdt`) in partially-filled cells because it would be misleading. In "icy" cells `tendency_of_ice_amount / density` and `dHdt` should be equal (possibly up to rounding errors).

You can confirm that a) `dHdt` as computed by PISM is a time average and b) it matches `tendency_of_ice_amount / density` by running this Bash script.

``` bash
#!/bin/bash

set -x
set -e

ncgen -o delta_P.nc - <<EOF
netcdf delta_P {
dimensions:
	time = UNLIMITED ; // (12 currently)
	nv = 2 ;
variables:
	double time(time) ;
		time:units = "days" ;
		time:axis = "T" ;
		time:calendar = "360_day" ;
		time:long_name = "time" ;
		time:bounds = "time_bounds" ;
	double delta_P(time) ;
		delta_P:units = "kg m-2 year-1" ;
	double time_bounds(time, nv) ;
data:
 time = 30,60,90,120,150,180,210,240,270,300,330,360;
 delta_P = 0,0,0,910,910,910,910,910,910,0,0,0;
 time_bounds = 0,30,30,60,60,90,90,120,120,150,150,180,180,
               210,210,240,240,270,270,300,300,330,330,360;
}
EOF

pisms -y 0 -Mx 3 -My 3 -Mz 3 -verbose 1 -o input.nc

pismr -i input.nc -bootstrap \
      -calendar 360_day \
      -y 1 \
      -max_dt $(echo "1 / 12" | bc -l) \
      -atmosphere uniform,delta_P \
      -atmosphere.uniform.precipitation 0 \
      -atmosphere.delta_P.file delta_P.nc \
      -surface simple \
      -extra_times $(( 2 * 30 * 86400 ))s \
      -extra_vars dHdt,tendency_of_ice_amount\
      -extra_file ex.nc \
      -o_size none

rm input.nc

ncap2 -O -s "diff = tendency_of_ice_amount/910 - dHdt" ex.nc ex.nc
```
