### ISSUE TITLE
When use PDD,it shows cannot convert 'mm day-1' to 'kg m-2 second-1'

### ISSUE THREAD

**Issue by zyastc213** [pism/pism#507]

**Comment by aaschwanden** [comment]
`mm day-1` cannot be converted to `kg m-2 second-1` because they are not compatible: one needs to multiply `mm day-1` (a rate) with a density. If your input is in `mm day-1` water equivalent, assume a density of `1000 kg m-3` and you can just change the unit attribute in the input file to `kg m-2 day-1` (a mass flux through an area).

**Comment by ckhroulev** [comment]
Please re-open this issue if it is still a problem.

**Comment by zyastc213** [comment]
> `mm day-1` cannot be converted to `kg m-2 second-1` because they are not compatible: one needs to multiply `mm day-1` (a rate) with a density. If your input is in `mm day-1` water equivalent, assume a density of `1000 kg m-3` and you can just change the unit attribute in the input file to `kg m-2 day-1` (a mass flux through an area).

thank you,if this is changed in pism2.0? because when i used the script from others(use version 0.7), the unit in the input file is mm day-1.

**Comment by ckhroulev** [comment]
@zyastc213 This change was introduced in PISM 1.0, i.e. in the next release after 0.7.
