### ISSUE TITLE
Consider using `kelvin` instead if `Kelvin` for units

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#544]
**Description**

`cf_xarray.units` which implements CF conforming units, has `Celsius`, but not `Kelvin`. Switching PISM's default from `Kelvin` to `kelvin` would allow seamless use of  `Xarray` in combination with `pint_xarray` and `cf_xarray`.

**PISM version**

PISMR (basic evolution run mode) 2.1.99-d7dc90a06

**To Reproduce**

In a shell:

`pismr -EisII A -o_size big_2d -o pism_test_pint_xarray.nc`
`pip install xarray cf_xarray pint_xarray`

In python:

```
import xarray as xr
import cf_xarray.units
import pint_xarray
ds = xr.open_dataset("pism_test_pint_xarray.nc")
for v in ds.data_vars:
    da = ds[v]
    da.pint.quantify()

ValueError: Cannot parse units:
    invalid units for variable 'shelfbtemp': Kelvin (attribute) (reason: 'Kelvin' is not defined in the unit registry)

```

**Comment by ckhroulev** [comment]
No objections. Note that [NIST](https://www.nist.gov/si-redefinition/kelvin-introduction) spells _kelvin_ with a lower case `k` and UDUNITS supports both "kelvin" and "Kelvin" (and `degree_Kelvin`, which, according to NIST, is wrong).

We should probably also replace "K" with "kelvin" in unit strings, for consistency (`pint` does recognize "K" as "kelvin", though.)

Another compatibility issue: UDUNITS parses `m s-2` as "m/s^2", i.e. a unit followed by an integer is interpreted as unit raised to a power. We should replace `m s-2` with `m s^-2` and so on. (UDUNITS recognizes `m2`, `m^2` and `m**2`, so this would not break anything. `pint` recognizes `m^2`, `m**2`, `m^-2`, etc, but not `m-2`.)

We should also replace "Celsius" with `degC` or `degree_Celsius` since `pint` does supports the latter two and not the first one.

PS: UDUNITS appears to be case-insensitive.

**Comment by ckhroulev** [comment]
The modified test script
``` python
import xarray as xr
import cf_xarray.units
import pint_xarray
import sys
ds = xr.open_dataset(sys.argv[1])

for v in ds.data_vars:
    if v == "hardav":
        continue
    print(da.pint.quantify())
```
works with PISM from the `dev` branch.

The "hardav" variable has units `pascal * second ^ (1/n)` where `n` is the Glen exponent.

Fractional powers are not supported by UDUNITS, so I'm not sure what to do about that. Setting units to `Pa s^0.333` or similar confuses UDUNITS because it interprets it as `Pa s^0 * 333 = 333 Pa`, while `Pa s^(1/3)` is not a valid UDUNITS string (but *is* a valid string according to `pint`.)

**Comment by aaschwanden** [comment]
I did not notice “Celsius” not being support because I had `cf_xarray` loaded, which supports `Celsius`.
But the default seems to be

$ cf_xarray.units.units.Celsius
$ degree_Celsius

I don’t have a strong opinion if we should go with “pure” pint, or CF units but I’m tending to CF. Since we are in the climate modeling community, CF would be OK, IMHO.  “degree_east” and similar are also only defined in `cf_xarray`.

**Comment by ckhroulev** [comment]
@aaschwanden CF conventions allow most units supported by UDUNITS (with some exceptions), so `degree_Celsius` is OK.

> The value of the units attribute is a string that can be recognized by the UDUNITS package [[UDUNITS]](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#UDUNITS), with the exceptions that are given in [Section 3.1.1, "Dimensionless units"](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#dimensionless-units) and [Section 3.1.3, "Scale factors and offsets"](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#units-multiples). Note that case is significant in the units strings.

(See [section 3.1. Units](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#units) for more.)

This works:
```
$ echo -e "degree_Celsius\nkelvin" | udunits2 
You have: You want:     1 degree_Celsius = 274.15 kelvin
    x/kelvin = (x/degree_Celsius) + 273.15
You have:
```

And this works too, so I think we're okay here.
```
$ python -c "import pint; print(pint.Unit('degree_Celsius'))"
degree_Celsius
```

**Comment by ckhroulev** [comment]
Done in the `dev` branch.
